sudo: false
language: generic
matrix:
  include:
  - os: linux
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
  timeout: 3600
before_install:
- travis_wait 45 bash ./utilities/travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
- latexmk -pdf -interaction=nonstopmode -halt-on-error manuscript.tex
after_success: 
deploy:
  provider: releases
  api_key:
    secure: Q8W7IUDslujUlAa5usKZipfLz1wRAIxeVKNvBpsS22PFcTbeM1hWpOS8zEMFEpCDV2FSN5B3S+TUb241cIxujTAtqkmkqHUo8Q/LBYF4NEahIJD9CMyB7H/8RfcOIRU5c2TutjpERfygbPyiJzVdYPD0MxMw0UxVLrHIqvGiXYXEHPbj5M8RziFHojCgeLc9Z7n3EVlCgbmA1tctUn7YoqIQuKdG11bwDtSRi0pKXJBKs4GeBGrWGd4t/+Vfo0xvz1GAvlRq3yxgZeX3BR1qoxl5q/y3dK3KvqL14oLlcAXce0hb5te2oQ7U7n3HEYgop+oYECs/pvPKzPg/453HulqmXysUAbbjyDA6ogFYsdfZyGeNsYXqrvYaUTy+PAnK1g6xazEYJX4G5QIdHc+UFy1VVFWqh3QLccOYTxQg1cAOXj8saf4BtjZ+s/ciD5TK+KflhJ5c7WnV4B/xL+kF5AXLuNmgxFfoRhOMrXUDH/Kd4Y7lTRQuJfEe9Oe/GDJylPgvSEgbm9LKADRMpfiU4rXPg49r59Ww6B44y5w51/6P7zltCADngRI7l2FP5EPkIyu03DjvVVqz564qijOD6cRrZZpQXTCjNYvIKsTXFDMyWYn9DyKsom/4CXOrahvw+JjwAj6TTVxPAMgdnqZUMh8NfCjDwtkBcItWFdiQ/SI=
  file: manuscript.pdf
  on:
    repo: skulumani/2018_sspi_manuscript
    tags: true
